WITH CTESTUDENTSELIGIBLE(PIDM, TERM_CODE) AS
  (SELECT TB.TBRACCD_PIDM,
    TB.TBRACCD_TERM_CODE AS TERM_CODE
  FROM
    (SELECT TBRACCD_PIDM,
      TBRACCD_TERM_CODE,
      SUM(TBRACCD_AMOUNT) AS TOTAL_BALANCE
    FROM TBRACCD
    WHERE TBRACCD_DETAIL_CODE='UPAS'
    GROUP BY TBRACCD_PIDM,
      TBRACCD_TERM_CODE
    )TB
  WHERE TB.TOTAL_BALANCE>'0'
  UNION ALL
    (SELECT LAKEHEAD.GWIDEN_PIDM,
      LAKEHEAD.STVTERM_CODE AS TERM_CODE
    FROM
      (SELECT G.GWIDEN_PIDM,
        T.STVTERM_CODE
      FROM GWIDEN G,
        STVTERM T
      WHERE G.GWIDEN_CONTRACT_CODE IN('LAKE','LUCS')
      AND (T.STVTERM_CODE           = G.GWIDEN_TERM_CODE
      OR (T.STVTERM_END_DATE       <= G.GWIDEN_EXPIRY_DATE
      AND T.STVTERM_CODE            > = G.GWIDEN_TERM_CODE
      AND MOD(T.STVTERM_CODE, 10)   = 0 ))
      )LAKEHEAD
    )
  UNION ALL
    (SELECT ESLG.GORVISA_PIDM,
      ESLG.SGBSTDN_TERM_CODE_EFF AS TERM_CODE
    FROM
      (SELECT GORVISA_PIDM, SGBSTDN_TERM_CODE_EFF
      FROM GORVISA GV
      JOIN SGBSTDN SG
      ON GV.GORVISA_PIDM          = SG.SGBSTDN_PIDM
      WHERE GV.GORVISA_PENT_CODE  = 'ARI'
      AND SG.SGBSTDN_MAJR_CODE_1 IN ('EAPC','ESLG')
      )ESLG
    )
  ),
  S_BUSPASS (PIDM, BUS_PASS_ELIGIBLE, TERM_CODE) AS
  ( SELECT DISTINCT PIDM, 'YES', TERM_CODE FROM CTESTUDENTSELIGIBLE
  )
SELECT A.SWRNVLL_ID,
  A.SWRNVLL_LNAME,
  GC_COMMON_PKG.FW_GET_PREFERRED_FIRST_NAME(SWRNVLL_ID),
  SPRIDEN_MI,
  SWRNVLL_MAJR,
  SWRNVLL_CAMP,
  GC_COMMON_PKG.FW_GET_GOREMAL_EMAIL_ADDRESS(SWRNVLL_PIDM,'COLL'),
  GC_COMMON_PKG.FW_GET_GOREMAL_EMAIL_ADDRESS(SWRNVLL_PIDM,'PR'),
  A.SWRNVLL_BIRTH_DATE,
  A.SWRNVLL_INTERNATIONAL,
  B.BUS_PASS_ELIGIBLE,
  T.STVTERM_START_DATE,
  T.STVTERM_END_DATE,
  TRUNC(TRUNC(T.STVTERM_START_DATE,'MM')-1,'MM') "BUS_PASS_START_DATE",
  LAST_DAY(T.STVTERM_END_DATE) "BUS_PASS_EXPIRATION_DATE"
FROM SWRNVLL A,
  SPRIDEN,
  S_BUSPASS B,
  STVTERM T
WHERE A.SWRNVLL_PIDM      = SPRIDEN_PIDM
AND B.PIDM              = A.SWRNVLL_PIDM
AND SPRIDEN_CHANGE_IND IS NULL
AND T.STVTERM_CODE      = B.TERM_CODE