SELECT T.TBRACCD_SURROGATE_ID,
    '2',
    S.SPRIDEN_ID,
    T.TBRACCD_AMOUNT,
    T.TBRACCD_TRANS_DATE
  FROM TAISMGR.TBRACCD T
  JOIN TAISMGR.TBBDETC D
  ON D.TBBDETC_DETAIL_CODE = T.TBRACCD_DETAIL_CODE
  JOIN TAISMGR.TTVDCAT C
  ON C.TTVDCAT_CODE = D.TBBDETC_DCAT_CODE
  JOIN SATURN.SPRIDEN S
  ON S.SPRIDEN_PIDM  = T.TBRACCD_PIDM
  WHERE TTVDCAT_CODE = 'ONE'
  AND S.SPRIDEN_CHANGE_IND IS NULL
  ORDER BY T.TBRACCD_TRANS_DATE desc